### ISSUE TITLE
Errors installing and starting up 1.20.4

### ISSUE THREAD

**Issue by lrirwin** [TheRemote/Legendary-Minecraft-Purpur-Geyser#12]
Bedrock version (1.20.62) does not work at this point.
Java version works with 1.20.4 even though these errors appear in the console:

[11:42:10 INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b95-71acc6c)
[11:42:10 ERROR]: Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b95-71acc6c) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[Floodgate-Spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2153]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
        at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:112) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[Floodgate-Spigot.jar:?]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R3.LoginListener$LoginHandler
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:390) ~[?:?]
        at java.lang.Class.forName(Class.java:381) ~[?:?]
        at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:110) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.util.ReflectionUtils.getClassOrFallback(ReflectionUtils.java:131) ~[Floodgate-Spigot.jar:?]
        at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:186) ~[Floodgate-Spigot.jar:?]
        ... 16 more
[11:42:10 INFO]: [floodgate] Disabling floodgate v2.2.2-SNAPSHOT (b95-71acc6c)
[11:42:10 INFO]: [ViaVersion] Enabling ViaVersion v4.9.3-SNAPSHOT
[11:42:10 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.3/1.20.4 (765)
[11:42:10 WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version!
[11:42:10 WARN]: [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.
[11:42:10 WARN]: [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too.
[11:42:10 WARN]: [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://viaversion.com/setup
[11:42:10 WARN]: [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.

**Comment by TheRemote** [comment]
This has been fixed in the latest version!
