### ISSUE TITLE
Docker container fails to load

### ISSUE THREAD

**Issue by LegacyKing** [TheRemote/Legendary-Minecraft-Purpur-Geyser#4]
Getting these errors with this container:

	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]

	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:215) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at java.lang.Thread.run(Unknown Source) ~[?:?]

	Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, falling-block-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"

		at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]

		at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]

		at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[purpur-1.19.2.jar:git-Purpur-1817]

		at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:215) ~[purpur-1.19.2.jar:git-Purpur-1817]

		at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1817]

		at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1817]

		at java.lang.Thread.run(Unknown Source) ~[?:?]

		Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, tnt-entity-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"

			at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]

			at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]

			at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[purpur-1.19.2.jar:git-Purpur-1817]

			at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:215) ~[purpur-1.19.2.jar:git-Purpur-1817]

			at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1817]

			at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1817]

			at java.lang.Thread.run(Unknown Source) ~[?:?]

		Caused by: java.lang.NumberFormatException: For input string: "disabled"

			at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]

			at java.lang.Integer.parseInt(Unknown Source) ~[?:?]

			at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]

			... 17 more

	Caused by: java.lang.NumberFormatException: For input string: "disabled"

		at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]

		at java.lang.Integer.parseInt(Unknown Source) ~[?:?]

		at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]

		... 17 more

Caused by: java.lang.NumberFormatException: For input string: "disabled"

	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]

	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]

	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]

	... 17 more

[17:33:32 ERROR]: 	Cause of unexpected exception was

java.lang.NumberFormatException: For input string: "disabled"

	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]

	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]

	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]

	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]

	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:215) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at java.lang.Thread.run(Unknown Source) ~[?:?]

[17:33:32 WARN]: Failed to get system info for World Generation

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null

	at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$11(MinecraftServer.java:1721) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1720) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1817]

	at java.lang.Thread.run(Unknown Source) ~[?:?]

[17:33:32 ERROR]: This crash report has been saved to: /minecraft/./crash-reports/crash-2022-10-09_17.33.32-server.txt

[17:33:32 INFO]: Stopping server

[17:33:32 INFO]: Saving players

[17:33:32 INFO]: Saving worlds

[17:33:32 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

[17:33:32 INFO]: Flushing Chunk IO

[17:33:32 INFO]: Closing Thread Pool

2022-10-09 17:33:33,001 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment

[17:33:32 INFO]: Closing Server

**Comment by TheRemote** [comment]
Does this happen on a new server?  

If I'm reading it correctly it's because "disabled" got typed into the file for the option "falling-block-height-nerf".  It's supposed to be a number and not a typed out string like that so it's crashing.

This option is not present in my default config files.  I tried this with a brand new server and I didn't get this error either so it seems like this is an invalid option that has been put in one of your config files here!

**Comment by LegacyKing** [comment]
I'll check that. I'm reusing a game volume. My existing server won't allow bedrock players on anymore. So, I was trying to jump to PurPur and see if that'd fix the issue.

**Comment by TheRemote** [comment]
Worst case scenario unless a new server won't work for you (I think it will) you could just copy the fresh default configs over the top to fix your existing server.

You'd have to redo any config changes you made but it would prevent you from having to start over or anything like that!

**Comment by LegacyKing** [comment]
Removing the problem entries resolved the issue. Thanks for the pointer so I could fix this!

**Comment by TheRemote** [comment]
No problem at all, thanks for confirming/leaving the solution as well as it will definitely help others in the future.

Enjoy and take care!
